version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - eventify-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eventifydb
      - SPRING_DATASOURCE_USERNAME=eventifyuser
      - SPRING_DATASOURCE_PASSWORD=eventifypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080

  frontend:
    build:
      context: ./EventifyFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - eventify-network
    environment:
      - VITE_API_URL=http://backend:8080/api/v1

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: eventifydb
      POSTGRES_USER: eventifyuser
      POSTGRES_PASSWORD: eventifypassword
    ports:
      - "5432:5432"
    networks:
      - eventify-network

networks:
  eventify-network:
    driver: bridge
